# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301c710de1baf3843c6494e98f6f534c45baf6c70d762ca4b162edcf38989f1c30351f30e533c6f758a7dfef5b7709dd5d0b829e112a8f85c4cabb8f9818f213

test:
  secret_key_base: 339e77ba1e7b852587389f4cc081e62c14dcc42cc73c1569d0fc5cbe24bb2e0ee452d7f2085228324c08ffb4c5d88f6496e0684586f753c17af842efa4fea6f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
